version: '3'
services:
  important:
    build:
      dockerfile: Dockerfile.important
    ports:
      - '8080:8080'
  oom:
    build:
      dockerfile: Dockerfile.oom
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          #pids: 1
        reservations:
          cpus: '0.25'
          memory: 20M
