version: '3'
services:
  important:
    image: perl:latest
    command:
      - bash
      - '-ce'
      - |
        cpanm -n Mojolicious && perl -Mojo -E 'a("/" => {text => "Very Important"})->start' daemon -l http://*:8080
    ports:
      - '8080:8080'
  oom:
    image: perl:latest
    command: perl -e 'fork() while fork()'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          #pids: 1
        reservations:
          cpus: '0.25'
          memory: 20M
